#include <stdio.h>
#include <string.h>

#define MAX 100

// estrutura do cliente
struct Cliente {
    int id;
        char nome[50];
            char telefone[20];
            };

            int main() {

                struct Cliente clientes[MAX];
                    int total = 0;
                        int opcao = 0;

                            while (opcao != 5) {

                                    // menu principal
                                            printf("\n1 - Cadastrar cliente\n");
                                                    printf("2 - Listar clientes\n");
                                                            printf("3 - Buscar cliente por ID\n");
                                                                    printf("4 - Excluir cliente\n");
                                                                            printf("5 - Sair\n");
                                                                                    printf("Escolha uma opcao: ");
                                                                                            scanf("%d", &opcao);
                                                                                                    getchar();

                                                                                                            // cadastrar
                                                                                                                    if (opcao == 1) {
                                                                                                                                if (total < MAX) {
                                                                                                                                                clientes[total].id = total + 1;

                                                                                                                                                                printf("Nome: ");
                                                                                                                                                                                fgets(clientes[total].nome, 50, stdin);
                                                                                                                                                                                                clientes[total].nome[strcspn(clientes[total].nome, "\n")] = '\0';

                                                                                                                                                                                                                printf("Telefone: ");
                                                                                                                                                                                                                                fgets(clientes[total].telefone, 20, stdin);
                                                                                                                                                                                                                                                clientes[total].telefone[strcspn(clientes[total].telefone, "\n")] = '\0';

                                                                                                                                                                                                                                                                total++;
                                                                                                                                                                                                                                                                                printf("Cliente cadastrado!\n");

                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                            printf("Limite atingido!\n");
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                // listar todos
                                                                                                                                                                                                                                                                                                                                        } else if (opcao == 2) {
                                                                                                                                                                                                                                                                                                                                                    if (total == 0) {
                                                                                                                                                                                                                                                                                                                                                                    printf("Nenhum cliente cadastrado.\n");
                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                int i;
                                                                                                                                                                                                                                                                                                                                                                                                                for (i = 0; i < total; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("\nID: %d\n", clientes[i].id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Nome: %s\n", clientes[i].nome);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Telefone: %s\n", clientes[i].telefone);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // buscar por id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (opcao == 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int busca, i, encontrado;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                encontrado = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Digite o ID: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        scanf("%d", &busca);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    getchar();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (i = 0; i < total; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (clientes[i].id == busca) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("\nID: %d\n", clientes[i].id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Nome: %s\n", clientes[i].nome);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Telefone: %s\n", clientes[i].telefone);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                encontrado = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (encontrado == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Cliente nao encontrado.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // excluir cliente
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (opcao == 4) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int busca, i, j, encontrado;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            encontrado = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Digite o ID para excluir: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%d", &busca);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                getchar();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (i = 0; i < total; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (clientes[i].id == busca) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (j = i; j < total - 1; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clientes[j] = clientes[j + 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    encontrado = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Cliente excluido!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (encontrado == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Cliente nao encontrado.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // opcao invalida
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (opcao != 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Opcao invalida!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Saindo...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        